<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ekf_pkg</name>
  <version>0.0.0</version>
  <description> This package contains the nodes that calculate the actual 
                and estimated pose of the object placed on the manipulator tray. 
                These include the pose estimation using the camera, 
                the force sensor at the wrist of the manipulator and 
                the extended kalman filter that performs the sensor fusion by combining them. 
                All the poses mentioned are estimated with respect to the centre of the tray. 
                In addition, there are nodes that calculate pose errors and a node 
                that respawns the object on the tray in the event of a fall.
  </description>
  <maintainer email="andreamazzera13@gmail.com">Andrea_Mazzera</maintainer>
  <license>Apache 2.0</license>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>apriltag_msgs</depend>
  <depend>visualization_msgs</depend>
  
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
