# Default initial positions 
id_controller_node:
  ros__parameters:
    joint_a1: 2.15
    joint_a2: 0.08
    joint_a3: -2.22
    joint_a4: -1.6
    joint_a5: 0.06
    joint_a6: -1.55
    joint_a7: 0.07
